### ISSUE TITLE
Realsense D435

### ISSUE THREAD

**Issue by SunshineDou** [johnbmcd/rssdk2klg#1]
Hello,
 Recently, I am doing a project about 3D reconstrcution, now I can run Kintinuous in Ubuntu16, our lab bought a Realsense D435 recently, I need to make my own dataset, so I need to get rgbd pictures from D435 and convert it to klg format, which can run in Kintinuous enviroment. I have a question the "rssdk2klg: can convert log file to klg format, is it suitable for me to make my own dataset? the log file comes from where?

Thank you very much!

**Comment by johnbmcd** [comment]
Yes it should be. We just used it on a R200 so can only confirm it working for that sensor however the SDK should be consistent across sensors. 

To capture a log file you should use the capture utility that comes as part of the Realsense sdk.

**Comment by SunshineDou** [comment]
Thanks very much for your replying. I have  configured the environment, and imported the  project, but when I started to run it, it failed ,it said: 
fatal error C1083: can not open file: “pxcsensemanager.h”: No such file or directory
1>RSSDKLog.cpp
where is the file"pxcsensemanager.h"? I cannot find it
